[project]
name = "dagster-contrib-azure"
description = "Community contributed Azure integration"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dagster>=1.9.0",
    "azure-mgmt-containerinstance>=10.1.0",
    "azure-identity>=1.12.0",
    "tenacity>=8.0.0",
]
dynamic = ["version"]

[tool.uv]
dev-dependencies = [
    "ruff",
    "pytest",
    "pyright>=1.1.386",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {exclude= ['dagster_contrib_azure_tests*']}

[tool.setuptools.dynamic]
version = {attr = "dagster_contrib_azure.__version__"}
